# Generated by Django 6.0.5 on 2026-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_threshold', models.PositiveIntegerField(default=30, help_text='Score minimum pour la bande MEDIUM')),
                ('high_threshold', models.PositiveIntegerField(default=60, help_text='Score minimum pour la bande HIGH')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du scoring',
                'verbose_name_plural': 'Configuration du scoring',
            },
        ),
    ]
