# Generated by Django 6.0.5 on 2026-05-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('INTERVENTION', 'Intervention'), ('FOLLOW_UP', 'Follow Up'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('risk_band', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10, null=True)),
                ('risk_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.CharField(choices=[('OK', 'ok'), ('DENIED', 'denied')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('grade_level', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.school')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.student'),
        ),
    ]
