# Generated by Django 6.0.5 on 2026-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absences_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='disciplinary_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_drop',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
