# Generated by Django 6.0.5 on 2026-06-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_student_absences_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='data_completeness',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
