# Generated by Django 6.0.5 on 2026-06-06 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_report_risksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevent',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]# Generated by Django 6.0.5 on 2026-06-06 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_report_risksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevent',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]