# Generated by Django 6.0.5 on 2026-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caseevent_entry_hash_caseevent_prev_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='integrity_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
