# Generated by Django 6.0.5 on 2026-06-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subject', models.CharField(max_length=80)),
                ('resource_type', models.CharField(choices=[('BOOK', 'Livre'), ('COURSE', 'Support de cours'), ('SUMMARY', 'Résumé')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('requested_role', models.CharField(choices=[('Student', 'Élève'), ('Teacher', 'Enseignant'), ('Counselor', 'Conseiller')], max_length=20)),
                ('student_code', models.CharField(blank=True, help_text='Pour les élèves : leur code dossier', max_length=40)),
                ('biography', models.TextField(help_text='Présentez-vous (vérification anti-bot)')),
                ('document', models.FileField(blank=True, null=True, upload_to='access_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, max_length=40)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0-100, plus haut = meilleur bien-être')),
                ('band', models.CharField(default='OK', max_length=10)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
