# Generated by Django 6.0.5 on 2026-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_governance', '0002_conversation_message_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('TEACHER', 'Enseignant'), ('COUNSELOR', 'Conseiller')], default='TEACHER', max_length=10),
        ),
    ]