# Generated by Django 6.0.5 on 2026-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_governance', '0003_conversation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='student_alias',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
