"""
Django settings for amal project.
Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY : en production, définir SECRET_KEY via une variable d'environnement.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-*-dt2%x@(#fuo98nnz-ksj9gtgd9^k^mr$^va6z)89kpn*r=!g'
)

# SECURITY : DEBUG=True seulement en développement. En prod : DEBUG=0 (variable d'env).
DEBUG = os.environ.get('DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

# Durcissement automatique en production (DEBUG=False) — n'affecte pas la démo locale.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Bibliothèques externes requises ---
    'rest_framework',
    
    # --- Les 5 couches applicatives (Architecture Amal) ---
    'app_intake',      # <-- Corrigé avec le préfixe
    'cases',           # <-- Déjà existant et fonctionnel
    'app_scoring',     # <-- Corrigé avec le préfixe
    'dashboard',       # <-- Déjà existant et fonctionnel
    'app_governance',  # <-- Corrigé avec le préfixe
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'amal.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'amal.wsgi.application'

# Database

# Par défaut SQLite (prototype, autorisé par le sujet). Pour passer à PostgreSQL,
# définir la variable d'environnement USE_POSTGRES=1 (+ les variables DB_*).
# Aucune ligne de logique métier ne change : seul ce bloc de configuration bascule.
if os.environ.get('USE_POSTGRES') == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'amal'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-fr' # Configuré en Français pour le contexte Tunisien

TIME_ZONE = 'Africa/Tunis' # Fuseau horaire local

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- NOUVEAU : CONFIGURATION DE LA CONNEXION ---
LOGIN_REDIRECT_URL = 'dashboard_router'  # <-- LA CORRECTION EST ICI !
LOGOUT_REDIRECT_URL = 'login'          
LOGIN_URL = 'login'